export default [
    {
        "_id": "Q101",
        "title": "Propulsion Quiz",
        "course": "RS101",
        "points": 100,
        "numberOfQuestions": 0,
        "accessCode": "ABC",
        "lockQuestionsAfterAnswering": false,
        "description": "Please answer the following questions.",
        "dueDate": "2025-05-07",
        "availableFromDate": "2025-05-01",
        "availableUntilDate": "2025-05-07",
        "quizType": "Graded Quiz",
        "assignmentGroup": "Quizzes",
        "shuffleAnswers": true,
        "timeLimit": 20,
        "multipleAttempts": true,
        "numberOfAttempts": 2,
        "showCorrectAnswers": true,
        "oneQuestionAtTime": true,
        "webcamRequired": false,
        "published": false
    },
    {
        "_id": "Q102",
        "title": "Combustion Analysis Quiz",
        "course": "RS101",
        "points": 100,
        "numberOfQuestions": 0,
        "accessCode": "ABC",
        "lockQuestionsAfterAnswering": false,
        "description": "Please answer the following questions.",
        "dueDate": "2025-05-13",
        "availableFromDate": "2025-05-07",
        "availableUntilDate": "2025-05-13",
        "quizType": "Graded Quiz",
        "assignmentGroup": "Quizzes",
        "shuffleAnswers": false,
        "timeLimit": 20,
        "multipleAttempts": true,
        "numberOfAttempts": 2,
        "showCorrectAnswers": true,
        "oneQuestionAtTime": true,
        "webcamRequired": false,
        "published": true
    },
    {
        "_id": "Q103",
        "title": "Nozzle Design Quiz",
        "course": "RS101",
        "points": 100,
        "numberOfQuestions": 0,
        "accessCode": "ABC",
        "lockQuestionsAfterAnswering": false,
        "description": "Please answer the following questions.",
        "dueDate": "2025-05-20",
        "availableFromDate": "2025-05-13",
        "availableUntilDate": "2025-05-20",
        "quizType": "Graded Quiz",
        "assignmentGroup": "Quizzes",
        "shuffleAnswers": true,
        "timeLimit": 40,
        "multipleAttempts": false,
        "numberOfAttempts": 1,
        "showCorrectAnswers": true,
        "oneQuestionAtTime": true,
        "webcamRequired": false,
        "published": true
    },
    {
        "_id": "Q201",
        "title": "Aerodynamics Quiz",
        "course": "RS102",
        "points": 100,
        "numberOfQuestions": 0,
        "accessCode": "ABC",
        "lockQuestionsAfterAnswering": false,
        "description": "Please answer the following questions.",
        "dueDate": "2025-05-07",
        "availableFromDate": "2025-05-01",
        "availableUntilDate": "2025-05-07",
        "quizType": "Graded Quiz",
        "assignmentGroup": "Quizzes",
        "shuffleAnswers": false,
        "timeLimit": 30,
        "multipleAttempts": true,
        "numberOfAttempts": 2,
        "showCorrectAnswers": false,
        "oneQuestionAtTime": true,
        "webcamRequired": false,
        "published": true
    },
    {
        "_id": "Q202",
        "title": "Flow Analysis Quiz",
        "course": "RS102",
        "points": 100,
        "numberOfQuestions": 0,
        "accessCode": "ABC",
        "lockQuestionsAfterAnswering": false,
        "description": "Please answer the following questions.",
        "dueDate": "2025-05-13",
        "availableFromDate": "2025-05-07",
        "availableUntilDate": "2025-05-13",
        "quizType": "Graded Quiz",
        "assignmentGroup": "Quizzes",
        "shuffleAnswers": false,
        "timeLimit": 15,
        "multipleAttempts": true,
        "numberOfAttempts": 3,
        "showCorrectAnswers": true,
        "oneQuestionAtTime": false,
        "webcamRequired": false,
        "published": true
    },
    {   "_id": "Q203",
        "title": "Heating Analysis Quiz",
        "course": "RS102",
        "points": 100,
        "numberOfQuestions": 0,
        "accessCode": "ABC",
        "lockQuestionsAfterAnswering": false,
        "description": "Please answer the following questions.",
        "dueDate": "2025-05-20",
        "availableFromDate": "2025-05-13",
        "availableUntilDate": "2025-05-20",
        "quizType": "Graded Quiz",
        "assignmentGroup": "Quizzes",
        "shuffleAnswers": false,
        "timeLimit": 20,
        "multipleAttempts": true,
        "numberOfAttempts": 3,
        "showCorrectAnswers": true,
        "oneQuestionAtTime": true,
        "webcamRequired": false,
        "published": true
    },
    {
        "_id": "Q301",
        "title": "Structural Design Task Quiz",
        "course": "RS103",
        "points": 100,
        "numberOfQuestions": 0,
        "accessCode": "ABC",
        "lockQuestionsAfterAnswering": false,
        "description": "Please answer the following questions.",
        "dueDate": "2025-05-07",
        "availableFromDate": "2025-05-01",
        "availableUntilDate": "2025-05-07",
        "quizType": "Graded Quiz",
        "assignmentGroup": "Quizzes",
        "shuffleAnswers": true,
        "timeLimit": 45,
        "multipleAttempts": false,
        "numberOfAttempts": 1,
        "showCorrectAnswers": true,
        "oneQuestionAtTime": true,
        "webcamRequired": false,
        "published": true
    },
    {
        "_id": "Q302",
        "title": "Orbital Calculations Quiz",
        "course": "RS103",
        "points": 100,
        "numberOfQuestions": 0,
        "accessCode": "ABC",
        "lockQuestionsAfterAnswering": false,
        "description": "Please answer the following questions.",
        "dueDate": "2025-05-13",
        "availableFromDate": "2025-05-07",
        "availableUntilDate": "2025-05-13",
        "quizType": "Graded Quiz",
        "assignmentGroup": "Quizzes",
        "shuffleAnswers": false,
        "timeLimit": 30,
        "multipleAttempts": true,
        "numberOfAttempts": 2,
        "showCorrectAnswers": true,
        "oneQuestionAtTime": true,
        "webcamRequired": false,
        "published": true },
    {
        "_id": "Q303",
        "title": "Systems Engineering Exam",
        "course": "RS103",
        "points": 100,
        "numberOfQuestions": 0,
        "accessCode": "ABC",
        "lockQuestionsAfterAnswering": false,
        "description": "Please answer the following questions.",
        "dueDate": "2025-05-20",
        "availableFromDate": "2025-05-13",
        "availableUntilDate": "2025-05-20",
        "quizType": "Graded Quiz",
        "assignmentGroup": "Exams",
        "shuffleAnswers": false,
        "timeLimit": 20,
        "multipleAttempts": false,
        "numberOfAttempts": 1,
        "showCorrectAnswers": true,
        "oneQuestionAtTime": true,
        "webcamRequired": false,
        "published": true }
]